require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PortionsController do

  # This should return the minimal set of attributes required to create a valid
  # Portion. As you add validations to Portion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "size" => "1.5" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PortionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all portions as @portions" do
      portion = Portion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:portions).should eq([portion])
    end
  end

  describe "GET show" do
    it "assigns the requested portion as @portion" do
      portion = Portion.create! valid_attributes
      get :show, {:id => portion.to_param}, valid_session
      assigns(:portion).should eq(portion)
    end
  end

  describe "GET new" do
    it "assigns a new portion as @portion" do
      get :new, {}, valid_session
      assigns(:portion).should be_a_new(Portion)
    end
  end

  describe "GET edit" do
    it "assigns the requested portion as @portion" do
      portion = Portion.create! valid_attributes
      get :edit, {:id => portion.to_param}, valid_session
      assigns(:portion).should eq(portion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Portion" do
        expect {
          post :create, {:portion => valid_attributes}, valid_session
        }.to change(Portion, :count).by(1)
      end

      it "assigns a newly created portion as @portion" do
        post :create, {:portion => valid_attributes}, valid_session
        assigns(:portion).should be_a(Portion)
        assigns(:portion).should be_persisted
      end

      it "redirects to the created portion" do
        post :create, {:portion => valid_attributes}, valid_session
        response.should redirect_to(Portion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved portion as @portion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portion.any_instance.stub(:save).and_return(false)
        post :create, {:portion => { "size" => "invalid value" }}, valid_session
        assigns(:portion).should be_a_new(Portion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portion.any_instance.stub(:save).and_return(false)
        post :create, {:portion => { "size" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested portion" do
        portion = Portion.create! valid_attributes
        # Assuming there are no other portions in the database, this
        # specifies that the Portion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Portion.any_instance.should_receive(:update_attributes).with({ "size" => "1.5" })
        put :update, {:id => portion.to_param, :portion => { "size" => "1.5" }}, valid_session
      end

      it "assigns the requested portion as @portion" do
        portion = Portion.create! valid_attributes
        put :update, {:id => portion.to_param, :portion => valid_attributes}, valid_session
        assigns(:portion).should eq(portion)
      end

      it "redirects to the portion" do
        portion = Portion.create! valid_attributes
        put :update, {:id => portion.to_param, :portion => valid_attributes}, valid_session
        response.should redirect_to(portion)
      end
    end

    describe "with invalid params" do
      it "assigns the portion as @portion" do
        portion = Portion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portion.any_instance.stub(:save).and_return(false)
        put :update, {:id => portion.to_param, :portion => { "size" => "invalid value" }}, valid_session
        assigns(:portion).should eq(portion)
      end

      it "re-renders the 'edit' template" do
        portion = Portion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portion.any_instance.stub(:save).and_return(false)
        put :update, {:id => portion.to_param, :portion => { "size" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested portion" do
      portion = Portion.create! valid_attributes
      expect {
        delete :destroy, {:id => portion.to_param}, valid_session
      }.to change(Portion, :count).by(-1)
    end

    it "redirects to the portions list" do
      portion = Portion.create! valid_attributes
      delete :destroy, {:id => portion.to_param}, valid_session
      response.should redirect_to(portions_url)
    end
  end

end
